theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  logo:
    header: "/assets/images/ajefa-horizontal.png"
    footer: "/assets/images/ajefa-horizontal.png"